Better quilt support
GroovyMC/ModsDotGroovy pull request #13
Opened 2022-11-05 03:21 UTC by lukebemish

I went through and improved support for `quilt.mod.json` files a bit; I don't *think* I made any breaking API changes, though I'm iffy on the changes to authors which break binary compat; I don't think those matter right now because as far as I know nobody is compiling against the DSL statically, but worth keeping in mind.

2022-11-12 10:29 UTC, Matyrobbrt requested changes

2022-11-12 10:29 UTC, Matyrobbrt commented on src/lib/groovy/modsdotgroovy/ImmutableQuiltModInfo.groovy
> +package modsdotgroovy
Missing license header

2022-11-21 22:41 UTC, PaintNinja approved these changes

2022-12-03 21:51 UTC, Matyrobbrt approved these changes

2022-12-03 22:22 UTC, merged